* SEPIC Converter
We are going to build a SEPIC converter using the LT3757. The main reason being, there are a lot of them available for relatively cheap, and the data sheet gives an explanation on how to do the math for a variety of architectures. With that let's get on with it.

First we must make a few design decisions, all of which will affect the size and efficiency of the converter. In general we want the converter to be as small as possible so it will fit nicely on the PCB. Efficiency is a bit of an after thought here, but a >70% efficiency would be preferred to reduce any excessive heating. The converter must be able to produce >40mA @ 180V from a 5V or 12V input, 5V is preferred since it would allow power over USB. With these constraints in mind we can make a quick list

    1) Input Voltage = 5V
    2) Output Voltage = 180V @ 40mA
    3) Switching Frequency = 700 kHz

The choice of 700 kHz for the switching frequency is in an attempt to reduce the size of the inductor required. A higher switching frequency allows for smaller inductor values but causes increased switching losses, reducing efficiency. 700 kHz is mostly a jumping off point for now and can be changed later in the design (perhaps made even fast if possible).

Now we go through the LT3757 datasheet and calculate all our component values. First the maximum duty cycle is calculated using the minimum input voltage as

    \begin{align*}
    D_{max}&=\frac{V_{out}+V_{D}}{V_{In(min)}+V_{out}+V_D} \\
    &=\frac{180+0.7}{5+180+0.7} \\
    &=0.973
    \end{align*}

where $$V_D$$ is the diode forward voltage assumed to be 0.7 V for now. Technically $$V_{in(min)}$$ may be a little bit lower than 5 V, but this is close enough for now.

** Inductors

Now we will determine the appropriate values for our inductors. For simplicity we are going to use separately wound inductors, although for space saving a single inductor may be used in a future design. From the datasheet we calculate the maximum current through the inductors $$L_1$$ and $$L_2$$ as

    \begin{align*}
    I_{L1(max)}&=I_{in(max)}=I_out(max)\frac{D_{max}}{1-D_{max}} \\
    &=0.04\cdot\frac{0.973}{1-0.973} \\
    &=1.4456 A \\
    I_{L2(max)}&=I_{out(max)} \\
    &=0.040A
    \end{align*}

and the maximum current is simply the sum of each maximum inductor current, making $$I_{SW(max)}=1.4856 A$$.

Now comes the slightly tricky part of picking a value for the maximum switch ripple current percentage, $$\chi$$. For now we will just stick with the recommendation of setting $$\chi=0.2$$ and will need to test the circuit later to find out if that should be changed. With the switch ripple current determined, we can calculate the peak switch current as

    \begin{align*}
    I_{SW(peak)}&=\left(1+\chi/2\right)I_{SW(max)} \\
    &=1.634 A.
    \end{align*}
    And the switch and inductor ripples are calculated as

    \begin{align*}
    \Delta I_{SW}&=\chi I_{SW(max)}=0.297 A \\
    \Delta I_{L1}&=\Delta I_{L2} = 0.5\cdot\Delta I_{SW} = 0.148 A
    \end{align*}

Finally we calculate the inductor value (this is where the switching frequency comes in)

\begin{align*}
L_1=L_2&=\frac{V_{in(min)}}{0.5\cdot\Delta I_{SW}\cdot f}\cdot D_{max} \\
&= \frac{5}{-0.5\cdot0.297\cdot 700,000}\cdot 0.973 \\
&=46.8 \mu H
\end{align*}

which is an awfully convenient value for an inductor since 47 uH inductors are readily available! Finally we need to calculate the peak and rms inductor currents

    \begin{align*}
    I_{L1(peak)}&=1.52 A \\
    I_{L2(peak)}&=0.144 A \\
I_{L1(rms)}&=1.446 A \\
I_{L2(rms)}&=0.058 A
    \end{align*}

which will be used later when looking for components.

Component choice is fairly easy here, just find a 47 uH inductor with saturation and current ratings above the peak current and rms current, respectively. Overshooting these rating should have no ill effect other than increasing the inductor size. Where possible the DC resistance should be minimized to reduce power loss due to heating. With these constraints in mind, I found the 104CDMCCDS-470MC to be appropriate for L1, with the advantage that it is relatively small. L2 is even easier since it handles much lower currents. I found the CBC3325T470KR to have acceptable parameters and it's in a 1210 form factor making it easy to solder.

** Sense Resistor

With the inductor values calculated, the sense resistor value can also be found as

    \begin{align*}
    R_{sense}=\frac{80 mV}{I_{SW(peak)}}=0.0488 \Omega
    \end{align*}
which is close enough to 50$$m\Omega$$, an easy to find resistor value.

** MOSFET

In order to choose a MOSFET to do the switching, we need to know how it's parameters will affect our efficiency. The power dissipated by the MOSFET is

\begin{align*}
P_{FET}&=I^2_{SW(max)}\cdot R_{DS(on)}\cdot D_{MAX} + 2\cdot(V_{in(min)}+V_{out})^2\cdotI_{L(max)}\cdotC_{RSS}\cdot f \\
&=2.147\cdot R_{DS(on)}+6.92\cdot10^{10}\cdot C_{RSS}
\end{align*}

where $$R_DS(on)$$ is the drain-source resistance and $$C_RSS$$ is the reverse transfer capacitance. Both values should be minimized to reduce power dissipation. Reducing $$R_DS(on)$$ is easy since many MOSFETs are in the milliOhm range, however more care must be taken with $$C_RSS$$ since it will need to be lower than ~15pF in order to keep power consumption near 1W. On top of power dissipation considerations, the Drain-Source breakdown voltage must be larger than the sum of the input and output voltages. A 220V or higher breakdown voltage should suffice.

Searching for an appropriate MOSFET can take a while since we are constantly calculating the total power dissipation for each MOSFET. That said, after a bit of search I landed on the TPN2010FNH which has a typical $$C_RSS=3pF$$ and a typical $$R_{DS(on)}=168 m\Omega$$, resulting in $$P_{FET}=0.568 W$$ which is good enough for now. As an added bonus, the MOSFET comes in a small surface mount package that will be easy to work with using a hot air gun or reflow oven. That said, if hand soldering were the only option, a different MOSFET should be chosen to make assembly easier.

** Output Diode

For choosing a diode we need to know the power it will dissipated and the peak current. Peak current is calculated as

\begin{align*}
I_{D(peak)}&=(1+\chi/2)\cdot I_{O(max)}\cdot\frac{1}{1-D_{max}} \\
&=1.630 A
\end{align*}

and the power dissipated is calculated as

\begin{align*}
P_D=I_{O(max)}\cdot V_D = 1.630\cdot V_D
\end{align*}

which indicates that to get good performance the forward drop voltage should be as low as possible. Also note that the peak repetitive reverse voltage ($$V_{RMM}$$) should be rated for the sum of the input and output voltages. For this application  $$V_{RMM}>220V$$ will suffice.

Using the above knowledge we can choose a diode by matching the $$V_{RMM}$$ and $$I_{D(peak)}$$ requirements. In addition, we want the diode to be small if possible. After a bit of searching on Digikey, I found the MURS3G-TP which seems to fit the bill. At the expected forward currents it has a $$V_D\approx 0.8V$$ which is decent given the voltage rating required. There are much better $$V_D$$ values on schottky diodes, however, most Schottky diodes don't satisfy the $$V_{RMM}$$ requirements (many have a $$V_{RMM}=200V$$ which is cutting it a bit close, if the design were to change to using 5V only perhaps a substitution can be made).

** Output capacitor

The output capacitor is important when considering the output ripple of the converter. For this we are particularly interested in the equivalent series resistance (ESR) of the capacitor. For our application a 1% ripple is acceptable, so the ESR can be calculated as

\begin{align*}
ESR_{Cout}\leq\frac{0.01\cdotV_{OUT}}{I_{D(peak)}}=\frac{0.01\cdot180}{1.630}=1.1\Omega
\end{align*}

The required capacitance, $$C_{out}$$ for a given 1% ripple is

\begin{align*}
C_{out}\geq\frac{I_{O(max)}}{0.01\cdotV_{out}\cdotf}=\frac{0.04}{0.01\cdot180\cdot 700,000}=31.7 nF
\end{align*}

And finally, the RMS current in the capacitor is calculated as

\begin{align*}
I_{RMS(Cout)}\geq I_{O(max)}\cdot\sqrt{\frac{D_{max}}{1-D_max}}=0.04\sqrt{\frac{0.973}{1-0.973}}=0.240A.
\end{align*}
These values are all well and good, although the minimum capacitance is quite low so it should be easy enough to find a capacitor that fits the bill. At such a low capaciatance, we might as well use a ceramic capacitor. It can be difficult to find all the necessary information on a capacitor (particularly ESR) so online tools such as [[https://ds.murata.co.jp/simsurfing/mlcc.html?lcid=en-us][this one]] provide nearly anything you could want to know about the capacitors. For example, the GRJ55DR72E105KWJ1L has an ESR below $$10m\Omega$$ and a capacitance of $$1 \mu F$$. Note the capacitor needs to be rated for the output voltage, in this case the capacitor is rated for 250V.

** DC Coupling Capacitor

The DC voltage rating for the coupling capacitor just needs to match the input voltage, so a 16V rated capacitor is fine. The RMS rating of the capacitor is calculated as

\begin{align*}
I_{RMS(CDC)}>I_{O(max)}\cdot\sqrt{\frac{V_{out}+V_{D}}{V_{in(min)}}}=0.24A
\end{align*}

Which is fairly easy to reach with a X5R ceramic capacitor. After checking the parameters, the GRM219R61C226ME15K will do the trick and has the added bonus of being used elsewhere in the design!

** Feedback Voltage Divider

The LT3757 needs a feedback line to make sure the output voltage is set correctly. To do this $$R_1$$ and $$R_2$$ are used as a voltage divider to reduce the voltage for the comparator. The values are calculated as

\begin{align*}
V_{out}&=1.6\cdot\left(1+\frac{R_2}{R_1}\right) \\
111.5\cdot R_1&=R_2
\end{align*}

As we can see, the exact values of the resistors is not too important, although $$R_1$$ should be kept below 158 k$$\Omega$$ according to the data sheet. Using a resistor ratio calculator, such as [[https://jansson.us/resistors.html][this one]], values of 1.8 $$k\Omega$$ and 200 $$k\Omega$$ are found for $$R_1$$ and $$R_2$$ respectively. Any 1% resistors will work for this, so lets use the RNCF0805DTE1K80 and the ERJ-6GEYJ204V.

** Other components

Now we find values and parts for the rest of the components. These aren't as important to the performance of the circuit so we'll do this fast

- Input Capacitor - GRM219R61C226ME15 - 22uF, 16V rated with a low enough ESR, a bit expensive so it can be switched for something cheaper
